# Generated by Django 4.1.13 on 2026-05-07 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=255)),
                ('is_provider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_qty', models.IntegerField(default=0)),
                ('loss_qty', models.IntegerField(default=0)),
                ('repaired_qty', models.IntegerField(default=0)),
                ('disposed_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/')),
                ('status', models.CharField(choices=[('REQUESTED', '승인대기'), ('APPROVED', '대여승인'), ('ACTIVE', '진행중'), ('CLOSED', '계약종료'), ('CANCELLED', '계약취소')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OUT', '출고'), ('RETURN', '반납')], max_length=10)),
                ('status', models.CharField(choices=[('OUT_CREATED', '출고 생성'), ('OUT_OFFICE_CHECKED', '사무실 확인완료'), ('OUT_OFFICE_SIGNED', '사무실 서명완료'), ('OUT_IN_TRANSIT', '현장 이동중'), ('OUT_SITE_RECEIVED', '현장 수령확인'), ('OUT_SITE_SIGNED', '현장 서명완료'), ('OUT_COMPLETED', '출고 완료'), ('RETURN_CREATED', '반납 생성'), ('RETURN_SITE_CHECKED', '현장 확인완료'), ('RETURN_SITE_SIGNED', '현장 서명완료'), ('RETURN_IN_TRANSIT', '공장 이동중'), ('RETURN_FACTORY_CHECKED', '공장 검수완료'), ('RETURN_OFFICE_SIGNED', '사무실 서명완료'), ('RETURN_COMPLETED', '반납 완료')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office_out_photo', models.ImageField(blank=True, null=True, upload_to='movements/out/')),
                ('office_out_signature', models.ImageField(blank=True, null=True, upload_to='signatures/out/')),
                ('site_receive_photo', models.ImageField(blank=True, null=True, upload_to='movements/receive/')),
                ('site_receive_signature', models.ImageField(blank=True, null=True, upload_to='signatures/receive/')),
                ('site_return_photo', models.ImageField(blank=True, null=True, upload_to='movements/return/')),
                ('site_return_signature', models.ImageField(blank=True, null=True, upload_to='signatures/return/')),
                ('office_in_photo', models.ImageField(blank=True, null=True, upload_to='movements/in/')),
                ('office_in_signature', models.ImageField(blank=True, null=True, upload_to='signatures/in/')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('siteWorker', '현장 직원'), ('siteManager', '현장 총책임자'), ('officeWorker', '사무실 직원'), ('officeManager', '사무실 총책임자'), ('superAdmin', '최고 관리자')], default='siteWorker', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.company')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.site')),
            ],
        ),
        migrations.CreateModel(
            name='RentalMovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_qty', models.IntegerField(default=0)),
                ('office_out_qty', models.IntegerField(default=0)),
                ('site_receive_qty', models.IntegerField(default=0)),
                ('site_request_return_qty', models.IntegerField(default=0)),
                ('return_qty', models.IntegerField(default=0)),
                ('final_in_qty', models.IntegerField(default=0)),
                ('loss_qty', models.IntegerField(default=0)),
                ('broken_qty', models.IntegerField(default=0)),
                ('repaired_qty', models.IntegerField(default=0)),
                ('discarded_qty', models.IntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_details', to='myapp.rentalmovement')),
                ('rental_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_details', to='myapp.rentaldetail')),
            ],
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='office_in_signed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_in_movements', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='office_out_signed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_out_movements', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='myapp.rental'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='site_receive_signed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_receive_movements', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='site_return_signed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_site_return_movements', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rental',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rentals', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rental',
            name='provider_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_rentals', to='myapp.company'),
        ),
        migrations.AddField(
            model_name='rental',
            name='requester_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_rentals', to='myapp.company'),
        ),
        migrations.AddField(
            model_name='rental',
            name='requester_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_rentals', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='rental',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='myapp.site'),
        ),
        migrations.CreateModel(
            name='AIRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_qty', models.IntegerField()),
                ('corrected_qty', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='ai/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movement_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='myapp.rentalmovementdetail')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_assignments', to='myapp.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='myapp.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sites', to='myapp.user')),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
    ]
