# Generated by Django 4.1.13 on 2026-05-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_airecognition_movement_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ACCEPTED', '처리완료')], default='PENDING', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='return_requests/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='return_requests/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user')),
            ],
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('REQUESTED', '승인대기'), ('APPROVED', '대여승인'), ('ACTIVE', '진행중'), ('COMPLETED', '거래완료'), ('CLOSED', '계약종료'), ('CANCELLED', '계약취소')], default='REQUESTED', max_length=20),
        ),
        migrations.CreateModel(
            name='ReturnRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_qty', models.IntegerField(default=0)),
                ('rental_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rentaldetail')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.returnrequest')),
            ],
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='myapp.rental'),
        ),
    ]
