# Generated by Django 4.1.13 on 2026-05-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_returnrequest_alter_rental_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecognition',
            name='return_request_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_results', to='myapp.returnrequestdetail'),
        ),
    ]
